  CREATE TABLE STAR_WARS (
           EPISODE_ID    NUMBER(5,0) NOT NULL,
           /*에피소드 아이디 숫자*/
	         EPISODE_NAME  VARCHAR2(50 BYTE), 
           /*영화 제목 문자*/
	         OPEN_YEAR     NUMBER(5,0), 
           /*개봉연도*/
	         CONSTRAINT STAR_WARS_PK PRIMARY KEY (EPISODE_ID));

  CREATE TABLE CHARACTERS (
         CHARACTER_ID    NUMBER NOT NULL, 
         /*등장인물 아이디 숫자*/
	       CHARACTER_NAME  VARCHAR2(30 BYTE), 
        /*등장인물 이름 문자*/
	       MASTER_ID       NUMBER(5,0), 
         /*제다이 아이디 숫자*/
	       ROLE_ID         NUMBER(5,0), 
         /*역할 아이디 숫자*/
	       EMAIL           VARCHAR2(40 BYTE), 
         /*등장인물 이메일 문자*/
	       CONSTRAINT CHARACTERS_PK PRIMARY KEY (CHARACTER_ID));

CREATE TABLE CASTING (
         EPISODE_ID    NUMBER(5,0)  NOT NULL, 
         /*에피소드 아이디 숫자*/
	       CHARACTER_ID  NUMBER(5,0)  NOT NULL,  
         /*등장인물 아이디 숫자*/
	       REAL_NAME     VARCHAR2(30 BYTE),
         /*등장인물 이름 문자*/
	       CONSTRAINT CASTING_PK PRIMARY KEY (EPISODE_ID, CHARACTER_ID));               

INSERT INTO STAR_WARS (EPISODE_ID, EPISODE_NAME, OPEN_YEAR)
VALUES(4,'새로운 희망(A NEW HOPE)', 1977);

INSERT INTO STAR_WARS (EPISODE_ID, EPISODE_NAME, OPEN_YEAR)
VALUES(5,'제국의 역습(The Empire Strikes Back)', 1980);

INSERT INTO STAR_WARS (EPISODE_ID, EPISODE_NAME, OPEN_YEAR)
VALUES(6,'제다이의 귀환(Return of the Jedi)', 1983);

INSERT INTO STAR_WARS (EPISODE_ID, EPISODE_NAME, OPEN_YEAR)
VALUES(1,'보이지 않는 위험(The Phantom Menace)', 1999);

INSERT INTO STAR_WARS (EPISODE_ID, EPISODE_NAME, OPEN_YEAR)
VALUES(2,'클론의 습격(Attack of the Clones)', 2002);

INSERT INTO STAR_WARS (EPISODE_ID, EPISODE_NAME, OPEN_YEAR)
VALUES(3,'시스의 복수(Revenge of the Sith)', 2005);

COMMIT;


INSERT INTO  CHARACTERS (CHARACTER_ID, CHARACTER_NAME, EMAIL )
VALUES(1, '루크 스카이워커','luke@jedai.com');
INSERT INTO  CHARACTERS (CHARACTER_ID, CHARACTER_NAME, EMAIL )
VALUES(2, '한 솔로','solo@alliance.com');
INSERT INTO  CHARACTERS (CHARACTER_ID, CHARACTER_NAME, EMAIL )
VALUES(3, '레이아 공주','leia@alliance.com');
INSERT INTO  CHARACTERS (CHARACTER_ID, CHARACTER_NAME, EMAIL )
VALUES(4, '오비완 케노비','Obi-Wan@jedai.com');
INSERT INTO  CHARACTERS (CHARACTER_ID, CHARACTER_NAME, EMAIL )
VALUES(5, '다쓰 베이더','vader@sith..com');
INSERT INTO  CHARACTERS (CHARACTER_ID, CHARACTER_NAME, EMAIL )
VALUES(6, '다쓰 베이더(목소리)','Chewbacca@alliance.com');
INSERT INTO  CHARACTERS (CHARACTER_ID, CHARACTER_NAME, EMAIL )
VALUES(7, 'C-3PO','c3po@alliance.com');
INSERT INTO  CHARACTERS (CHARACTER_ID, CHARACTER_NAME, EMAIL )
VALUES(8, 'R2-D','r2d2@alliance.com');
INSERT INTO  CHARACTERS (CHARACTER_ID, CHARACTER_NAME, EMAIL )
VALUES(9, '츄바카','Chewbacca@alliance.com');
INSERT INTO  CHARACTERS (CHARACTER_ID, CHARACTER_NAME, EMAIL )
VALUES(10, '랜도 칼리시안', NULL);
INSERT INTO  CHARACTERS (CHARACTER_ID, CHARACTER_NAME, EMAIL )
VALUES(11, '요다(목소리)','yoda@jedai.com');
INSERT INTO  CHARACTERS (CHARACTER_ID, CHARACTER_NAME, EMAIL )
VALUES(12, '다스 시디어스', NULL);
INSERT INTO  CHARACTERS (CHARACTER_ID, CHARACTER_NAME, EMAIL )
VALUES(13, '아나킨 스카이워커','Anakin@jedai.com');
INSERT INTO  CHARACTERS (CHARACTER_ID, CHARACTER_NAME, EMAIL )
VALUES(14, '카와곤 진', NULL);
INSERT INTO  CHARACTERS (CHARACTER_ID, CHARACTER_NAME, EMAIL )
VALUES(15, '아미달라 여왕', NULL);
INSERT INTO  CHARACTERS (CHARACTER_ID, CHARACTER_NAME, EMAIL )
VALUES(16, '아나킨 어머니', NULL);
INSERT INTO  CHARACTERS (CHARACTER_ID, CHARACTER_NAME, EMAIL )
VALUES(17, '자자빙크스(목소리)', 'jaja@jedai.com');
INSERT INTO  CHARACTERS (CHARACTER_ID, CHARACTER_NAME, EMAIL )
VALUES(18, '다스 몰', NULL);
INSERT INTO  CHARACTERS (CHARACTER_ID, CHARACTER_NAME, EMAIL )
VALUES(19, '장고 펫', NULL);
INSERT INTO  CHARACTERS (CHARACTER_ID, CHARACTER_NAME, EMAIL )
VALUES(20, '마스더 윈두','windu@jedai.com');
INSERT INTO  CHARACTERS (CHARACTER_ID, CHARACTER_NAME, EMAIL )
VALUES(21, '듀크 백작','dooku@jedai.com');

COMMIT;

CREATE TABLE ROLES ( 
ROLE_ID  NUMBER(5,0) NOT NULL, 
ROLE_NAME VARCHAR(30 BYTE), 
CONSTRAINT ROLES_PK PRIMARY KEY (ROLE_ID));


INSERT INTO  ROLES (ROLE_ID, ROLE_NAME)
VALUES(1001, '제다이');

INSERT INTO  ROLES (ROLE_ID, ROLE_NAME)
VALUES(1002, '시 스');

INSERT INTO  ROLES (ROLE_ID, ROLE_NAME)
VALUES(1003, '반란군');

COMMIT;

ALTER TABLE CHARACTERS
ADD CONSTRAINT CHARACTER_FK FOREIGN KEY (ROLE_ID)
REFERENCES ROLES(ROLE_ID);

UPDATE CHARACTERS
SET role_id = 1001
WHERE character_id IN (1,4,11,13,17,20,21);

UPDATE CHARACTERS
SET role_id = 1002
WHERE character_id IN(5,6,12,18);

UPDATE CHARACTERS
SET role_id = 1002
WHERE character_id IN (2,3,7,8,9);

COMMIT;

UPDATE CHARACTERS
   SET MASTER_ID = 4
 WHERE CHARACTER_ID = 13;
 
UPDATE CHARACTERS
   SET MASTER_ID = 4
 WHERE CHARACTER_ID = 1;
 
UPDATE CHARACTERS
   SET MASTER_ID = 11
 WHERE CHARACTER_ID = 20; 
 
UPDATE CHARACTERS
   SET MASTER_ID = 11
 WHERE CHARACTER_ID = 21;  
 
UPDATE CHARACTERS
   SET MASTER_ID = 12
 WHERE CHARACTER_ID = 5;  

UPDATE CHARACTERS
   SET MASTER_ID = 12
 WHERE CHARACTER_ID = 18;  
 
UPDATE CHARACTERS
   SET MASTER_ID = 14
 WHERE CHARACTER_ID = 4;  
 
UPDATE CHARACTERS
   SET MASTER_ID = 21
 WHERE CHARACTER_ID = 14;  

COMMIT;

ALTER TABLE CASTING
ADD CONSTRAINT CASTING_FK1 FOREIGN KEY (EPISODE_ID)
REFERENCES STAR_WARS(EPISODE_ID);

ALTER TABLE CASTING
ADD CONSTRAINT CASTING_FK2 FOREIGN KEY (CHARACTER_ID)
REFERENCES CHARACTERS(CHARACTER_ID);

COMMIT;

